# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1534a5123b240885c095dbc0bd9100c03425ffbd709acb854e9fca3e7981dfc9dccb454ea98d79cabab21537579e531bfc8c4fbd0d3063458d2c8cdd2ba46b6f

test:
  secret_key_base: 3007263af41d20197332aed07419a62388e9e978019d75d681715298d6f75546a4580b273dd1fd02f78d2b99f62d2cac27c12849cd46b3363aa78e5838d92c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
